### ISSUE TITLE
没有添加权限申请，6.0以上点击保存图片失败

### ISSUE THREAD

**Issue by totond** [dangxy/Readhub#2]
```
01-05 10:46:00.451 12660-12660/com.dangxy.readhub W/System.err: java.io.IOException: open failed: EACCES (Permission denied)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at java.io.File.createNewFile(File.java:942)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at com.dangxy.readhub.utils.ViewUtils.saveBitmap(ViewUtils.java:200)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at com.dangxy.readhub.model.DetailActivity$1.accept(DetailActivity.java:55)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at io.reactivex.internal.observers.LambdaObserver.onNext(LambdaObserver.java:63)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at com.jakewharton.rxbinding2.view.ViewClickObservable$Listener.onClick(ViewClickObservable.java:39)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at android.view.View.performClick(View.java:5264)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at android.view.View$PerformClick.run(View.java:21297)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at android.os.Handler.handleCallback(Handler.java:743)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at android.os.Looper.loop(Looper.java:150)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5621)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:794)
01-05 10:46:00.452 12660-12660/com.dangxy.readhub W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:684)
01-05 10:46:00.453 12660-12660/com.dangxy.readhub W/System.err: Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
01-05 10:46:00.453 12660-12660/com.dangxy.readhub W/System.err:     at libcore.io.Posix.open(Native Method)
01-05 10:46:00.453 12660-12660/com.dangxy.readhub W/System.err:     at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
01-05 10:46:00.453 12660-12660/com.dangxy.readhub W/System.err:     at java.io.File.createNewFile(File.java:935)
01-05 10:46:00.453 12660-12660/com.dangxy.readhub W/System.err: 	... 13 more
```

发现项目中的RxPermission没有用到，我加上去就好了，要提交pr么

**Comment by dangxy** [comment]
这个在规划中了 周末抽空我一起提交了 多谢

**Comment by dangxy** [comment]
@totond  已经修复了 可以看一下
